// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAsHAYp7Dg5h0rpn2JXb1xCtt5W2rBl1E',
    appId: '1:908501604231:web:a05868ea8b143e1477a522',
    messagingSenderId: '908501604231',
    projectId: 'food-delivery-app-6cba5',
    authDomain: 'food-delivery-app-6cba5.firebaseapp.com',
    storageBucket: 'food-delivery-app-6cba5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqMIVkyDvYO-tYTwvbLg3RuXKbjO3Oss',
    appId: '1:908501604231:android:82f03db22eb21f8f77a522',
    messagingSenderId: '908501604231',
    projectId: 'food-delivery-app-6cba5',
    storageBucket: 'food-delivery-app-6cba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6ZBdpNJ24ScvbNXhwY7uRrBb6O3HP7c',
    appId: '1:908501604231:ios:5e935a28e2c37cc077a522',
    messagingSenderId: '908501604231',
    projectId: 'food-delivery-app-6cba5',
    storageBucket: 'food-delivery-app-6cba5.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6ZBdpNJ24ScvbNXhwY7uRrBb6O3HP7c',
    appId: '1:908501604231:ios:5e935a28e2c37cc077a522',
    messagingSenderId: '908501604231',
    projectId: 'food-delivery-app-6cba5',
    storageBucket: 'food-delivery-app-6cba5.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAsHAYp7Dg5h0rpn2JXb1xCtt5W2rBl1E',
    appId: '1:908501604231:web:3bf57f797c16b67c77a522',
    messagingSenderId: '908501604231',
    projectId: 'food-delivery-app-6cba5',
    authDomain: 'food-delivery-app-6cba5.firebaseapp.com',
    storageBucket: 'food-delivery-app-6cba5.firebasestorage.app',
  );
}
